"""
This module defines the SessionStateResponse model, which represents the structure of a response for session state,
including unique thread and run IDs generated by Azure Foundry.
"""

from typing import Optional

from pydantic import BaseModel, Field


class SessionStateResponse(BaseModel):
    """
    Represents the response for a session state, including optional thread and run IDs generated by Azure Foundry.
    """

    threadId: Optional[str] = Field(
        None,
        description="Identificador único del hilo de conversación generado por Azure Foundry",
    )
    runId: Optional[str] = Field(
        None,
        description="Identificador único de la ejecución del agente en Azure Foundry",
    )
